<?php

namespace App\Exports;

use App\Models\Resident;
use App\Models\Household;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Concerns\WithMultipleSheets;

class CensusExport implements WithMultipleSheets
{
    public function sheets(): array
    {
        return [
            new CensusSummarySheet(),
            new CensusDetailSheet(),
        ];
    }
}

class CensusSummarySheet implements FromCollection, WithHeadings, WithTitle
{
    public function collection()
    {
        return collect([
            ['Total Population', Resident::count()],
            ['Total Households', Household::count()],
            ['Average Household Size', round(Household::avg('total_members'), 2)],
            ['', ''],
            ['Gender Distribution', ''],
            ['Male', Resident::where('sex', 'male')->count()],
            ['Female', Resident::where('sex', 'female')->count()],
            ['', ''],
            ['Age Groups', ''],
            ['Children (0-12)', Resident::where('age', '<', 13)->count()],
            ['Teens (13-19)', Resident::whereBetween('age', [13, 19])->count()],
            ['Adults (20-59)', Resident::whereBetween('age', [20, 59])->count()],
            ['Senior Citizens (60+)', Resident::where('age', '>=', 60)->count()],
            ['', ''],
            ['Special Categories', ''],
            ['PWD', Resident::where('is_pwd', true)->count()],
            ['Voters', Resident::where('is_voter', true)->count()],
            ['4Ps Beneficiaries', Resident::where('is_4ps_beneficiary', true)->count()],
            ['', ''],
            ['Employment Status', ''],
            ['Employed', Resident::where('employment_status', 'employed')->count()],
            ['Unemployed', Resident::where('employment_status', 'unemployed')->count()],
            ['Self-Employed', Resident::where('employment_status', 'self-employed')->count()],
            ['Students', Resident::where('employment_status', 'student')->count()],
            ['Retired', Resident::where('employment_status', 'retired')->count()],
            ['', ''],
            ['Housing', ''],
            ['Owned', Household::where('housing_type', 'owned')->count()],
            ['Rented', Household::where('housing_type', 'rented')->count()],
            ['Rent-Free', Household::where('housing_type', 'rent-free')->count()],
            ['With Electricity', Household::where('has_electricity', true)->count()],
            ['Without Electricity', Household::where('has_electricity', false)->count()],
            ['', ''],
            ['Generated', now()->format('F d, Y h:i A')],
            ['Generated By', auth()->user()->name],
        ]);
    }

    public function headings(): array
    {
        return ['Category', 'Count'];
    }

    public function title(): string
    {
        return 'Census Summary';
    }
}

class CensusDetailSheet implements FromCollection, WithHeadings, WithTitle
{
    public function collection()
    {
        return Resident::with('household')->get()->map(function ($resident) {
            return [
                'resident_id' => $resident->resident_id,
                'full_name' => $resident->full_name,
                'age' => $resident->age,
                'sex' => ucfirst($resident->sex),
                'civil_status' => ucfirst($resident->civil_status),
                'household_id' => $resident->household->household_id,
                'address' => $resident->household->full_address,
                'is_household_head' => $resident->is_household_head ? 'Yes' : 'No',
                'is_pwd' => $resident->is_pwd ? 'Yes' : 'No',
                'is_senior' => $resident->is_senior_citizen ? 'Yes' : 'No',
                'is_voter' => $resident->is_voter ? 'Yes' : 'No',
                'is_4ps' => $resident->is_4ps_beneficiary ? 'Yes' : 'No',
                'occupation' => $resident->occupation,
                'monthly_income' => $resident->monthly_income,
            ];
        });
    }

    public function headings(): array
    {
        return [
            'Resident ID',
            'Full Name',
            'Age',
            'Sex',
            'Civil Status',
            'Household ID',
            'Address',
            'Household Head',
            'PWD',
            'Senior Citizen',
            'Voter',
            '4Ps',
            'Occupation',
            'Monthly Income'
        ];
    }

    public function title(): string
    {
        return 'Residents Detail';
    }
}
